### ISSUE TITLE
Crash upon import

### ISSUE THREAD

**Issue by lebigot** [conda-forge/uncertainties-feedstock#11]
There is currently a crash at import time with Python 2, because the source of uncertainties/core.py in the Conda Forge distribution differs from the original source: https://github.com/lebigot/uncertainties/issues/77.

The problem comes more precisely from the fact that [the original source](https://github.com/lebigot/uncertainties/blob/7112a2faeaccea7d458951cf86ad5902ef6bbb39/uncertainties/core.py#L925) has all its Unicode string markers `u"…"` removed: each string below should have it, as in the original source:
```python
# Maps some Unicode code points ("-", "+", and digits) to their
# superscript version:
TO_SUPERSCRIPT = {
    0x2b: '⁺',
    0x2d: '⁻',
    0x30: '⁰',
    0x31: '¹',
    0x32: '²',
    0x33: '³',
    0x34: '⁴',
    0x35: '⁵',
    0x36: '⁶',
    0x37: '⁷',
    0x38: '⁸',
    0x39: '⁹'
    }
```

**Comment by ocefpaf** [comment]
I wonder if making this `noarch` is the culprit. Is there any Python version specific checking in the code?

**Comment by rth** [comment]
I can confirm this happens for Python 2.7 for uncertainties 3.0.2 (built with noarch) but not for uncertainties 3.0.1 (build without). 

I didn't know noarch could do something like this...

**Comment by rth** [comment]
Also shouldn't the `import uncertainties` test have failed at build time?

**Comment by ocefpaf** [comment]
PR #12 should fix this. Thanks @rh for checking!

**Comment by ocefpaf** [comment]
> Also shouldn't the `import uncertainties` test have failed at build time?

`noarch` packages are tested with the python present at build time, so in this case it was Python 3.6, no failures there.
