### ISSUE TITLE
Small but significant bug preventing inverse matrices in conda-forge version (see fix in comment)

### ISSUE THREAD

**Issue by AdityaSavara** [conda-forge/uncertainties-feedstock#22]
Issue:

I installed my version using 
`conda install -c conda-forge uncertainties`

I tried to follow the example: for uncertainties with inverse using this syntax:
uncertainties.unumpy.ulinalg.inv([[ufloat(2, 0.1)]])

I was getting this error when I tried to do matrix inverses with uncertainties:
`TypeError: unsupported operand type(s) for |=: 'set' and 'list'`

Tracing it, I found a line like this in core.py around line 387:

`variables |= list(element.derivatives.keys())`

I found that changing it to this fixed the problem:

`variables |= set(element.derivatives.keys())`

System: Python 3.5.6, Windows 10,

**Comment by ocefpaf** [comment]
You should report that upstream. Here we just package it.

**Comment by lebigot** [comment]
uncertainties 3.1.3 on conda should be downgraded to 3.1.2: I introduced a packaging bug in 3.1.3, and later removed this version. The PyPI version is thus 3.1.2. This should be the same for the latest conda package.

**Comment by ocefpaf** [comment]
Good to know. We moved it to broken. Thanks!
