### ISSUE TITLE
Version string wrong

### ISSUE THREAD

**Issue by RSully** [conda-forge/uncertainties-feedstock#3]
2.4.8 should be 2.4.8.1 and the download URL adjusted to remove the extra ".1". Per @ocefpaf here: https://github.com/conda-forge/conda-forge.github.io/pull/197#issuecomment-234115392

**Comment by ocefpaf** [comment]
Quoting @ocefpaf.

> I will fix that soon.

:unamused: 

Thanks for the ping. Fixing it now!
