### ISSUE TITLE
Uncertainties 3.0.1 is not available for linux-32 or linux-64

### ISSUE THREAD

**Issue by bryanwweber** [conda-forge/uncertainties-feedstock#6]
Hello,

According to the list here: https://anaconda.org/conda-forge/uncertainties/files uncertainties 3.0.1 is only available for Windows and OS X. I presume this was due to a problem in the CI upload. Is there any way to retrigger the build to upload the new version?

Also, the CircleCI build failed: https://circleci.com/gh/conda-forge/uncertainties-feedstock/10

Thanks!

**Comment by ocefpaf** [comment]
Thanks for noticing. I restarted CircleCI and the packages should be up
soon.

PS: but we do not build Linux-32

**Comment by bryanwweber** [comment]
OK no problem, I only need linux-64 anyways. The packages are uploaded now, so I'll close this issue. Thanks for the fast reply!

**Comment by ocefpaf** [comment]
Thank you for the report. If you are interested in this package health
consider adding yourself as a maintainer  (a PR adding your GitHub handle
in the recipe maintainers list.)

That will give you the power to merge updates and restart CIs, which would
allow you to solve this issue by yourself
; -)
